# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForm():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_form(self):
    # Test name: form
    # Step # | name | target | value | comment
    # 1 | open | /forms/d/e/1FAIpQLScDCQdVDnrt5i3j0T9YJgP65Aev_7STwc3EgBT-aO1lgnwQ-A/viewform |  | 
    self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLScDCQdVDnrt5i3j0T9YJgP65Aev_7STwc3EgBT-aO1lgnwQ-A/viewform")
    # 2 | setWindowSize | 912x694 |  | 
    self.driver.set_window_size(912, 694)
    # 3 | click | name=entry.1691379449 |  | 
    self.driver.find_element(By.NAME, "entry.1691379449").click()
    # 4 | type | name=entry.1691379449 | Akash | 
    self.driver.find_element(By.NAME, "entry.1691379449").send_keys("Akash")
    # 5 | type | name=entry.2137693010 | Globallogic | 
    self.driver.find_element(By.NAME, "entry.2137693010").send_keys("Globallogic")
    # 6 | click | css=.freebirdFormviewerViewItemsRadioOptionContainer:nth-child(1) .docssharedWizToggleLabeledLabelText |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormviewerViewItemsRadioOptionContainer:nth-child(1) .docssharedWizToggleLabeledLabelText").click()
    # 7 | click | css=.isSelected > .quantumWizMenuPaperselectContent |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".isSelected > .quantumWizMenuPaperselectContent").click()
    # 8 | click | css=.exportSelectPopup > .isSelected > .quantumWizMenuPaperselectContent |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".exportSelectPopup > .isSelected > .quantumWizMenuPaperselectContent").click()
    # 9 | click | name=entry.211057078 |  | 
    self.driver.find_element(By.NAME, "entry.211057078").click()
    # 10 | type | name=entry.211057078 | mastermindvishu97@gmail.com | 
    self.driver.find_element(By.NAME, "entry.211057078").send_keys("mastermindvishu97@gmail.com")
    # 11 | click | css=.appsMaterialWizButtonPaperbuttonLabel |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".appsMaterialWizButtonPaperbuttonLabel").click()
    # 12 | close |  |  | 
    #self.driver.close()
  
