# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAsdas():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_asdas(self):
    # Test name: asdas
    # Step # | name | target | value | comment
    # 1 | open | /forms/d/e/1FAIpQLScDCQdVDnrt5i3j0T9YJgP65Aev_7STwc3EgBT-aO1lgnwQ-A/viewform |  | 
    self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLScDCQdVDnrt5i3j0T9YJgP65Aev_7STwc3EgBT-aO1lgnwQ-A/viewform")
    # 2 | setWindowSize | 1382x744 |  | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | css=.isSelected |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".isSelected").click()
    # 4 | click | css=.exportSelectPopup > .isSelected > .quantumWizMenuPaperselectContent |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".exportSelectPopup > .isSelected > .quantumWizMenuPaperselectContent").click()
  
